### ISSUE TITLE
Missing documentation for special character: Background

### ISSUE THREAD

**Issue by niecore** [Rahix/tbot#25]

**Comment by Rahix** [comment]
Hi!

I think I've left it out of documentation because it has a few nasty side-effects.  If a program in the background still outputs to the console, this will silently break things.  Ideally, a proper `Background` special symbol would always redirect output to prevent all console clobbering.  E.g.

```python
# Automatically adds redirects to /dev/null
m.exec0("python", "-m", "http.server", linux.Background)

# Redirect stdout
m.exec0("python", "-m", "http.server", linux.Background(stdout="/tmp/http.log"))

# Redirect stdout & stderr
m.exec0("python", "-m", "http.server", linux.Background(stdout="/tmp/http.log", stderr="/tmp/http-error.log"))
```

But this, of course, needs to be implemented first ...

**Comment by Rahix** [comment]
Finally got around to adding this:  https://tbot.tools/modules/machine_linux.html#tbot.machine.linux.Background
